[2025-02-06T15:41:05.262+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T15:41:05.279+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-06T15:41:00.352353+00:00 [queued]>
[2025-02-06T15:41:05.289+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-06T15:41:00.352353+00:00 [queued]>
[2025-02-06T15:41:05.292+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T15:41:05.314+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-02-06 15:41:00.352353+00:00
[2025-02-06T15:41:05.321+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-06T15:41:05.323+0000] {standard_task_runner.py:72} INFO - Started process 8130 to run task
[2025-02-06T15:41:05.323+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_que_faire_a_paris', 'load_data', 'manual__2025-02-06T15:41:00.352353+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/dag_que_faire_a_paris.py', '--cfg-path', '/tmp/tmpqw_qv1gn']
[2025-02-06T15:41:05.325+0000] {standard_task_runner.py:105} INFO - Job 116: Subtask load_data
[2025-02-06T15:41:05.396+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_que_faire_a_paris.load_data manual__2025-02-06T15:41:00.352353+00:00 [running]> on host b176106a6d6f
[2025-02-06T15:41:05.575+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_que_faire_a_paris' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-06T15:41:00.352353+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-06T15:41:00.352353+00:00'
[2025-02-06T15:41:05.576+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T15:41:05.593+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-02-06T15:41:06.860+0000] {dag_que_faire_a_paris.py:185} INFO - âœ… Loading completed successfully!
[2025-02-06T15:41:06.863+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-06T15:41:06.878+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T15:41:06.879+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_que_faire_a_paris, task_id=load_data, run_id=manual__2025-02-06T15:41:00.352353+00:00, execution_date=20250206T154100, start_date=20250206T154105, end_date=20250206T154106
[2025-02-06T15:41:06.945+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-06T15:41:06.968+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-06T15:41:06.973+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
